In [11]:
student = {
    "name": "Ram",
    "age": 20,
    "faculty": "BCE"
}

In [11]:
import sys
print(sys.executable)

/Users/gautamsah/Desktop/Machine learning/.venv/bin/python

In [2]:
!{sys.executable} -m pip install pandas

zsh:1: parse error near `-m'

In [1]:
import pandas as pd

In [12]:
df = pd.DataFrame([student])

In [13]:
df.head()

  name  age faculty
0  Ram   20     BCE

In [14]:
df.tail()

  name  age faculty
0  Ram   20     BCE

In [15]:
df.shape

(1, 3)

In [16]:
df.columns

Index(['name', 'age', 'faculty'], dtype='str')

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     1 non-null      str
 1   age      1 non-null      int64
 2   faculty  1 non-null      str
dtypes: int64(1), str(2)
memory usage: 156.0 bytes

In [18]:
df.describe()

        age
count   1.0
mean   20.0
std     NaN
min    20.0
25%    20.0
50%    20.0
75%    20.0
max    20.0

In [19]:
df["name"]

0    Ram
Name: name, dtype: str

In [23]:
df[['name', 'age']]

  name  age
0  Ram   20